import { StyleSheet } from "react-native";

const QuizStyles = StyleSheet.create({
    container: {
        flexGrow: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 10,
        marginTop: 0,
        height: '100%',
        backgroundColor: 'white',
    },
    questionTitle: {
        fontSize: 26,
        paddingVertical: 10,
        alignSelf: 'flex-start',
        marginHorizontal: 28,
        marginTop: 20,
    },
    question: {
        alignSelf: 'flex-start',
        paddingVertical: 10, 
        marginHorizontal: 30,
        fontSize: 18,
    },
    optionsContainer: {
        alignSelf: 'flex-start',
        marginHorizontal: 30,
        marginBottom: 20,
    },
    optionText: {
        fontSize: 18,
        paddingVertical: 5,
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    selectedButton: {
        backgroundColor: '#1E3A8A',
    },
    selectedButtonText: {
        color: '#f2f2f2',
    },
    button: {
        backgroundColor: '#F2F2F2',
        paddingVertical: '10',
        paddingHorizontal: '30',
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        height: 45,
        marginHorizontal: 10,
        marginVertical: 15,
        minWidth: '40%',
        borderWidth: 0.25,
        borderColor: 'black',
    },
    buttonNav: {
        backgroundColor: '#F2F2F2',
        paddingVertical: '5',
        paddingHorizontal: '15',
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        height: 35,
        marginVertical: 15,
        marginStart: 25,
        minWidth: '20%',
        alignSelf: 'flex-start',
    },
    buttonText: {
        color: 'black',
        fontSize: 16,
    },
    buttonNext: {
        backgroundColor: '#FF6F00',
        paddingVertical: '10',
        paddingHorizontal: '30',
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        margin: 15,
        minWidth: '40%',
        alignSelf: 'flex-end',
        marginEnd: 30,
    },
    buttonNextText: {
        color: '#F2F2F2',
        fontSize: 16,
        fontWeight: 'bold'
    },
    progressBar: {
        alignSelf: 'flex-start',
        marginStart: 28,
        marginTop: 10,
    },
    hiddenButton: {
       opacity: 0, 
    },
    resultContainer: {
        width: '75%',
        flex: 1,
        backgroundColor: '#fff',
        padding: 25,
        borderRadius: 15,
        alignItems: 'center',
        elevation: 5,
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 5,
        justifyContent: 'center',
        marginTop: 100,
        marginBottom:50,
    },
    closeButton: {
        position: 'absolute',
        top: 60, 
        right: 55,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        padding: 5,
        borderRadius: 20,
        zIndex: 10,
    },
    closeButtonText: {
        color: '#fff',
        fontSize: 22,
        fontWeight: 'bold',
    },
    quizBackground: {
        backgroundColor: 'white', 
    },
    resultsBackground: {
        backgroundColor: '#1E3A8A',
    },
    resultEmoji: {
        fontSize: 100, 
        textAlign: 'center',
        marginBottom: 10,
    },
    resultStyleName: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1E3A8A',  
    },
    resultText: {
        fontSize: 22,
        textAlign: 'center',
        lineHeight: 28,
        color: 'black', 
        lineHeight: 40,
    },
    retakeQuizButton: {
        backgroundColor: '#FF6F00',
        paddingVertical: '10',
        paddingHorizontal: '30',
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        marginTop: 40,
        minWidth: '40%',
    },
    retakeQuizButtonText: {
        color: '#fff',
    },
    disabledButton: {
        backgroundColor: '#f2f2f2',
        borderWidth: '0.25',
    },
    disabledButtonText: {
        color: 'black',
        fontWeight: 'regular',
    }
})

export default QuizStyles;